LINK_REGISTRATION = "https://web.teambooktest.com/register"
LINK_LOGIN = "https://web.teambooktest.com/login"
LINK_PROFILE = "https://web.teambooktest.com/profile"
LINK_PLANNING = "https://web.teambooktest.com/planners/5209/2023-11-20"
LINK_PROJECTS = "https://web.teambooktest.com/projects"
